### ISSUE TITLE
Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $

### ISSUE THREAD

**Issue by akbarnash** [haerulmuttaqin/MyPets-App#1]
saat delete data muncul notif seperti itu, data berhasil terhapus namun activity tidak otomatis berpindah ke MainActivity, dimanakah saya harus menambahkan **JsonReader.setLenient(true)**?

**Comment by haerulmuttaqin** [comment]
Respon / output yang di kasih sama php mu ada yang kurang betul / bukan
format json.
